[client]
toolbarMode = "viewer"
[browser]
gatherUsageStats = false

[server]
runOnSave = true
headless = true

[theme]
base = "dark"
#primaryColor = ""
#backgroundColor = ""
#secondaryBackgroundColor = ""
#textColor = ""
font = "sans serif"
